# apiVersion: networking.istio.io/v1
# kind: VirtualService
# metadata:
#   name: nginx
# spec:
#   hosts:
#   - nginx-active
#   gateways:
#   - mesh
#   http:
#   - match:
#     - headers:
#         x-preview:
#           exact: "true"
#     route:
#     - destination:
#         host: nginx-preview
#   - route:
#     - destination:
#         host: nginx-active


apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx
spec:
  hosts:
  - nginx
  gateways:
  - mesh
  http:
  - name: default
    route:
    - destination:
        host: nginx
        subset: stable
      weight: 100
    - destination:
        host: nginx
        subset: canary
      weight: 0
