apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: nginx
  namespace: nginx-prod
spec:
  hosts:
  - app.example.com
  - nginx.nginx-prod.svc.cluster.local  
  gateways:
  - nginx-prod-gateway
  - mesh
  http:
  - name: default
    route:
    - destination:
        host: nginx.nginx-prod.svc.cluster.local
        subset: stable
      weight: 100
    - destination:
        host: nginx.nginx-prod.svc.cluster.local
        subset: canary
      weight: 0
