apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: nginx
spec:
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: { duration: 30s }
      - setWeight: 30
      - pause: { duration: 1m }
      - setWeight: 60
      - pause: { duration: 2m }
      - setWeight: 100
      trafficRouting:
        istio:
          virtualService:
            name: nginx
            routes:
            - primary
