apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-base
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: 'https://istio-release.storage.googleapis.com/charts'
      chart: base
      targetRevision: 1.24.0
      helm:
        valueFiles:
          - $values/platform/istio/base-values.yaml # Ensure there is a space after the '-'
    - repoURL: 'https://github.com/ankit96khokhar/gitops'
      targetRevision: main
      ref: values # This 'ref' maps to '$values' used above
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true