apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx-fleet
  namespace: argocd
spec:
  goTemplate: true

  generators:
  - matrix:
      generators:
      - git:
          repoURL: https://github.com/ankit96khokhar/gitops
          revision: main
          files:
            - path: apps_final/*/*/base/kustomization.yaml

      - list:
          elements:
            - env: dev
            - env: prod

  template:
    metadata:
      name: '{{index (splitList "/" .path.path) 1}}-{{.env}}-{{index (splitList "/" .path.path) 2}}'
      labels:
        customer: '{{index (splitList "/" .path.path) 1}}'
        service: '{{index (splitList "/" .path.path) 2}}'
        env: '{{.env}}'

    spec:
      project: default

      source:
        repoURL: https://github.com/ankit96khokhar/gitops
        targetRevision: main
        path: 'apps_final/{{index (splitList "/" .path.path) 1}}/{{index (splitList "/" .path.path) 2}}/overlays/{{.env}}'

      destination:
        server: https://kubernetes.default.svc
        namespace: '{{index (splitList "/" .path.path) 1}}-{{.env}}'

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true