apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: my-redis
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  redis:
    replicas: 3
  sentinel:
    replicas: 3

