apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-servicemonitors
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ankit96khokhar/gitops
    targetRevision: main
    path: platform/observability/servicemonitors
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
