apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-envoy
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    any: true
  selector:
    matchLabels:
      istio-prometheus: "true"
  endpoints:
    - port: http-envoy-prom
      path: /stats/prometheus
      interval: 30s