apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.jenkins.io' # Official Jenkins Helm Repo
    targetRevision: 5.8.17              # Specify a stable version
    chart: jenkins
    helm:
      values: |
        controller:
          serviceType: NodePort          # Better for Minikube access
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: jenkins-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    createNamespace: true